// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Revenu } from "./Revenu";
import type { TempsGestion } from "./TempsGestion";

/**
 * Un adulte du foyer, avec ses revenus et son rapport au risque.
 */
export type Adulte = { prenom: string, age: number, revenus: Array<Revenu>, 
/**
 * 1 = indépendant / variable … 3 = CDI / fonctionnaire.
 */
stab_revenus: number, 
/**
 * 1 = « je vends à -20 % » … 5 = « je renforce ».
 */
tol_risque: number, temps_gestion: TempsGestion, abondement_employeur: boolean, };
