// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Gravite } from "./Gravite";

export type Alerte = { gravite: Gravite, message: string, };
