// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Répartition par ligne (fractions ou montants selon le contexte).
 */
export type Allocation = { etf_monde: number, fonds_euros_obligations: number, immobilier: number, or: number, actions_directes: number, crowdfunding: number, crypto: number, private_equity: number, };
