// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VerdictCredit } from "./VerdictCredit";

/**
 * Lecture d'un crédit : coût réel, cohérence de la saisie et arbitrage.
 */
export type AnalyseCredit = { libelle: string, objet_libelle: string, 
/**
 * « Foyer » ou le nom de la SCI qui porte le crédit.
 */
porte_par: string, taux_pct: number, restant_du_eur: number, mensualite_eur: number, duree_restante_mois: number, 
/**
 * Intérêts restant à payer jusqu'au terme.
 */
interets_restants_eur: number, 
/**
 * Mensualité recalculée à partir du taux, du restant dû et de la durée.
 */
mensualite_theorique_eur: number, 
/**
 * Faux si la mensualité saisie s'écarte trop de la mensualité théorique.
 */
coherent: boolean, verdict: VerdictCredit, verdict_libelle: string, commentaire: string, };
