// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Avoirs financiers actuels du foyer (hors résidence principale, hors capital déjà affecté
 * aux études et aux projets).
 */
export type Avoirs = { 
/**
 * Livret A, LDDS, LEP… (épargne de précaution).
 */
livrets: number, 
/**
 * Liquidités à investir (compte courant excédentaire, cash PEA/CTO).
 */
liquidites_a_investir: number, etf_monde: number, fonds_euros_obligations: number, scpi: number, or: number, actions_directes: number, crowdfunding_immo: number, crowdfunding_enr: number, crypto: number, private_equity: number, };
