// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Bien vendable : le locatif détenu en direct, ou les biens d'une SCI.
 * La résidence principale est hors périmètre (elle changerait aussi le budget logement).
 */
export type BienVendu = { "type": "locatif_direct" } | { "type": "sci", id: string, };
