// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RegimeSci } from "./RegimeSci";

/**
 * Situation annuelle d'une SCI, du point de vue du foyer.
 */
export type BilanSci = { id: string, nom: string, regime: RegimeSci, regime_libelle: string, part_foyer: number, 
/**
 * Valeur des biens + SCPI − capital restant dû, en quote-part du foyer.
 */
valeur_nette_eur: number, 
/**
 * Parts de SCPI détenues, en quote-part du foyer.
 */
scpi_eur: number, loyers_annuels_eur: number, charges_annuelles_eur: number, interets_annuels_eur: number, 
/**
 * IS : dotation aux amortissements de l'exercice.
 */
amortissement_annuel_eur: number, 
/**
 * Assiette imposable : résultat foncier (IR) ou résultat fiscal (IS).
 */
resultat_imposable_eur: number, impot_annuel_eur: number, 
/**
 * Trésorerie de la société après charges, crédit et impôt de la société.
 */
tresorerie_annuelle_eur: number, 
/**
 * Ce que le foyer touche réellement, net d'impôt, par mois.
 */
cash_flow_foyer_mensuel_eur: number, 
/**
 * IS : résultat conservé dans la société (patrimoine, mais pas un revenu passif).
 */
capitalise_annuel_eur: number, 
/**
 * Effort d'épargne mensuel que le foyer doit apporter (trésorerie négative).
 */
effort_mensuel_eur: number, 
/**
 * Mensualités de crédit portées par la SCI, en quote-part du foyer.
 */
mensualites_mensuelles_eur: number, commentaires: Array<string>, };
