// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PosteBudget } from "./PosteBudget";
import type { RevenuAdulte } from "./RevenuAdulte";

export type Budget = { adultes: Array<RevenuAdulte>, total_revenus_eur: number, 
/**
 * Dépenses regroupées par poste (postes vides omis).
 */
postes: Array<PosteBudget>, total_depenses_eur: number, mensualites_credits_eur: number, capacite_calculee_eur: number, epargne_retenue_eur: number, epargne_forcee: boolean, 
/**
 * Épargne retenue / revenus.
 */
taux_epargne: number, 
/**
 * Capacité calculée non épargnée (si l'épargne imposée est plus faible).
 */
non_affecte_eur: number, };
