// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Produit d'une vente programmée, du point de vue du foyer.
 */
export type Cession = { libelle: string, bien_libelle: string, dans_ans: number, part_vendue: number, 
/**
 * Prix de vente retenu à l'échéance (prix d'aujourd'hui revalorisé).
 */
prix_vente_eur: number, frais_vente_eur: number, 
/**
 * Capital restant dû du ou des crédits soldés à la vente.
 */
credit_solde_eur: number, 
/**
 * Base imposable : prix − prix d'acquisition (IR) ou − valeur nette comptable (IS).
 */
plus_value_brute_eur: number, 
/**
 * IS : amortissements réintégrés dans la plus-value.
 */
amortissements_reintegres_eur: number, 
/**
 * Abattement pour durée de détention appliqué (0 à l'IS).
 */
abattement_eur: number, impot_eur: number, regime_libelle: string, 
/**
 * Ce qui reste au foyer, après frais, crédit et impôt.
 */
produit_net_eur: number, 
/**
 * Revenu passif mensuel qui disparaît avec le bien.
 */
cash_flow_perdu_mensuel_eur: number, 
/**
 * Mensualités qui cessent d'être dues (crédit soldé).
 */
mensualites_liberees_eur: number, commentaires: Array<string>, };
