// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Contraintes = { esg: boolean, refus_crypto: boolean, refus_immo_direct: boolean, 
/**
 * Part de crypto souhaitée dans la poche 2 (%), plafonnée par les hypothèses.
 */
crypto_souhaitee_pct: number, };
