// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PosteDepense } from "./PosteDepense";

/**
 * Dépense courante mensuelle du foyer, hors mensualités de crédit (saisies dans les crédits).
 */
export type Depense = { poste: PosteDepense, libelle: string, montant_mensuel: number, };
