// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObjetCredit } from "./ObjetCredit";

export type Dette = { libelle: string, taux_pct: number, restant_du: number, mensualite: number, 
/**
 * Nombre de mensualités restantes. 0 = durée inconnue (le crédit est alors
 * supposé courir jusqu'au bout de la projection).
 */
duree_restante_mois: number, objet: ObjetCredit, 
/**
 * Identifiant de la SCI qui porte le crédit ; `None` = crédit du foyer.
 */
sci_id: string | null, };
