// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TypeEcole } from "./TypeEcole";

export type Enfant = { prenom: string, age: number, type_ecole: TypeEcole, logement_etudiant: boolean, 
/**
 * Années à financer (prépa + école).
 */
duree_etudes: number, 
/**
 * Capital déjà mis de côté pour cet enfant (€).
 */
capital_deja_affecte: number, };
