// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Priorite } from "./Priorite";

export type FluxProjet = { nom: string, priorite: Priorite, besoin_eur: number, montant_eur: number, };
