// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PalierGlide } from "./PalierGlide";
import type { ProfilParams } from "./ProfilParams";

export type Hypotheses = { age_debut_etudes: number, frais_scolarite_public: number, frais_scolarite_prive: number, frais_scolarite_mixte: number, cout_logement_annuel: number, inflation_etudes: number, 
/**
 * Inflation appliquée au montant des projets datés.
 */
inflation_projets: number, rendement_actions: number, rendement_securise: number, 
/**
 * Paliers triés par horizon décroissant.
 */
glide_path: Array<PalierGlide>, prudent: ProfilParams, equilibre: ProfilParams, dynamique: ProfilParams, 
/**
 * score ≤ seuil → Prudent.
 */
seuil_score_prudent: number, 
/**
 * score > seuil → Dynamique.
 */
seuil_score_dynamique: number, h_fire_court: number, h_fire_long: number, precaution_mois_min: number, precaution_mois_defaut: number, precaution_mois_max: number, seuil_taux_dette: number, endettement_max: number, age_regle_actions: number, actions_max_tolerance_faible: number, plancher_fonds_euros: number, plancher_fonds_euros_horizon_court: number, or_min: number, or_max: number, crowdfunding_max: number, actions_directes_max: number, satellites_max: number, crypto_max: number, immo_max: number, immo_max_gestion_elevee: number, seuil_concentration_immo: number, tolerance_reequilibrage: number, plafond_pea: number, pfu: number, prelevements_sociaux: number, abattement_av_seul: number, abattement_av_couple: number, abattement_donation: number, plafond_per_revenus: number, annees_derisquage: number, annees_coussin: number, };
