// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnalyseCredit } from "./AnalyseCredit";
import type { BilanSci } from "./BilanSci";
import type { Cession } from "./Cession";

/**
 * Patrimoine immobilier : détention directe, SCI et ventes programmées.
 */
export type Immobilier = { locatif_direct_net_eur: number, cash_flow_direct_mensuel_eur: number, scis: Array<BilanSci>, 
/**
 * Somme des valeurs nettes, quote-part du foyer.
 */
total_net_eur: number, 
/**
 * Revenu passif immobilier réellement perçu par le foyer.
 */
cash_flow_total_mensuel_eur: number, 
/**
 * Effort d'épargne mensuel absorbé par les SCI en trésorerie négative.
 */
effort_scis_mensuel_eur: number, 
/**
 * Résultat conservé chaque année dans les SCI à l'IS (patrimoine, pas revenu).
 */
capitalise_scis_annuel_eur: number, ventes: Array<Cession>, credits: Array<AnalyseCredit>, };
