// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lignes de la poche 2.
 */
export type Ligne = "etf_monde" | "fonds_euros_obligations" | "immobilier" | "or" | "actions_directes" | "crowdfunding" | "crypto" | "private_equity";
