// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ligne } from "./Ligne";

export type LigneAllocation = { ligne: Ligne, libelle: string, cible_pct: number, actuelle_pct: number, ecart_points: number, actuel_eur: number, cible_eur: number, 
/**
 * Répartition proposée des liquidités à déployer (stock).
 */
deploiement_eur: number, 
/**
 * Répartition du flux mensuel poche 2.
 */
flux_mensuel_eur: number, 
/**
 * Ligne fermée aux nouveaux apports.
 */
gelee: boolean, enveloppe: string, support: string, };
