// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ce que finance le crédit : le levier n'a pas le même sens sur un bien qui rapporte
 * que sur une voiture.
 */
export type ObjetCredit = "residence_principale" | "locatif" | "consommation" | "autre";
