// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PalierGlide = { 
/**
 * Le palier s'applique quand l'horizon (années) est ≥ cette valeur.
 */
horizon_min_ans: number, part_actions: number, };
