// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Profil } from "./Profil";

export type PhaseRevenus = { annee_derisquage: number, profil_phase: Profil, retrait_annuel_eur: number, retrait_mensuel_eur: number, coussin_fonds_euros_eur: number, abattement_av_eur: number, ordre_sources: Array<string>, regles: Array<string>, };
