// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Poche0 = { cible_mois: number, cible_eur: number, existant_eur: number, 
/**
 * Montant manquant (> 0) pour atteindre la cible.
 */
manque_eur: number, 
/**
 * Montant au-delà de la cible, redéployable en poche 2.
 */
excedent_eur: number, supports: Array<string>, };
