// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Allocation } from "./Allocation";
import type { DetailScore } from "./DetailScore";
import type { Levier } from "./Levier";
import type { LigneAllocation } from "./LigneAllocation";
import type { PointProjection } from "./PointProjection";
import type { Profil } from "./Profil";

export type Poche2 = { profil: Profil, profil_libelle: string, score: number, detail_score: Array<DetailScore>, rendement_attendu: number, perte_max_plausible: number, revenu_manquant_mensuel: number, capital_cible_eur: number, 
/**
 * Capital financier actuel pris en compte (hors locatif direct).
 */
capital_financier_actuel_eur: number, 
/**
 * Base des pourcentages : financier poche 2 + immobilier locatif net.
 */
base_allocation_eur: number, epargne_mensuelle_necessaire_eur: number, 
/**
 * Flux actuel vers la poche 2 une fois les projets en cours financés.
 */
flux_disponible_regime_eur: number, 
/**
 * Flux moyen vers la poche 2 d'ici l'échéance (projets terminés = flux libéré).
 */
flux_moyen_simule_eur: number, 
/**
 * Capital simulé à l'échéance avec l'épargne du foyer.
 */
capital_projete_eur: number, atteignable: boolean, allocation_cible: Allocation, allocation_actuelle: Allocation, lignes: Array<LigneAllocation>, ajustements: Array<string>, leviers: Array<Levier>, projection: Array<PointProjection>, reequilibrage_necessaire: boolean, };
