// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PointProjection = { annee: number, capital_flux_disponible: number, capital_epargne_necessaire: number, cible: number, };
