// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PosteDepense } from "./PosteDepense";

export type PosteBudget = { poste: PosteDepense, libelle: string, montant_eur: number, 
/**
 * Part des revenus du foyer.
 */
part_revenus: number, };
