// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Allocation } from "./Allocation";

export type ProfilParams = { allocation: Allocation, 
/**
 * Rendement nominal attendu long terme, avant fiscalité.
 */
rendement: number, 
/**
 * Perte maximale plausible sur 12 mois (valeur négative).
 */
perte_max: number, };
