// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Priorite } from "./Priorite";

/**
 * Projet daté du foyer (voiture, travaux, apport, voyage…).
 */
export type Projet = { libelle: string, 
/**
 * Montant en euros d'aujourd'hui.
 */
montant: number, 
/**
 * Échéance, en années à partir d'aujourd'hui.
 */
dans_ans: number, priorite: Priorite, capital_deja_affecte: number, };
