// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Adulte } from "./Adulte";
import type { Avoirs } from "./Avoirs";
import type { Contraintes } from "./Contraintes";
import type { Depense } from "./Depense";
import type { Dette } from "./Dette";
import type { Enfant } from "./Enfant";
import type { Projet } from "./Projet";
import type { StatutRp } from "./StatutRp";
import type { Tmi } from "./Tmi";

export type Questionnaire = { adultes: Array<Adulte>, tmi: Tmi, rp: StatutRp, lep_eligible: boolean, depenses: Array<Depense>, 
/**
 * Épargne mensuelle imposée ; `None` = revenus − dépenses − mensualités.
 */
epargne_mensuelle_forcee: number | null, 
/**
 * Années avant de réduire le temps de travail.
 */
h_fire: number, 
/**
 * Revenu passif mensuel visé pour le foyer (net, €/mois).
 */
r_cible: number, taux_retrait_pct: number, autres_revenus_passifs: number, enfants: Array<Enfant>, projets: Array<Projet>, avoirs: Avoirs, 
/**
 * Valeur nette (valeur − capital restant dû) de l'immobilier locatif.
 */
v_immo_loc: number, 
/**
 * Cash-flow net mensuel du locatif (après crédit, charges, impôts).
 */
cf_immo: number, dettes: Array<Dette>, contraintes: Contraintes, };
