// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Régime fiscal de la SCI. Le choix change tout : à l'IR les loyers sont imposés
 * chaque année chez les associés ; à l'IS la société amortit le bien et n'impose
 * les associés qu'au moment de la distribution.
 */
export type RegimeSci = "ir" | "is";
