// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FluxProjet } from "./FluxProjet";

export type RepartitionFlux = { total_eur: number, precaution_eur: number, remboursement_dettes_eur: number, projets: Array<FluxProjet>, poche_2_eur: number, etapes: Array<string>, };
