// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Alerte } from "./Alerte";
import type { Budget } from "./Budget";
import type { PhaseRevenus } from "./PhaseRevenus";
import type { Poche0 } from "./Poche0";
import type { Poche2 } from "./Poche2";
import type { RepartitionFlux } from "./RepartitionFlux";
import type { SousPoche } from "./SousPoche";
import type { Synthese } from "./Synthese";

export type Resultat = { synthese: Synthese, budget: Budget, poche_0: Poche0, poche_1: Array<SousPoche>, poche_2: Poche2, flux: RepartitionFlux, priorite_enveloppes: Array<string>, phase_revenus: PhaseRevenus, alertes: Array<Alerte>, };
