// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TempsGestion } from "./TempsGestion";

export type RevenuAdulte = { prenom: string, montant_eur: number, part: number, tol_risque: number, stab_revenus: number, temps_gestion: TempsGestion, };
