// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Revenu = { libelle: string, 
/**
 * Net mensuel (moyenne lissée sur l'année pour les primes).
 */
montant_mensuel: number, };
