// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RegimeSci } from "./RegimeSci";

/**
 * Société civile immobilière détenant de l'immobilier locatif et/ou des parts de SCPI.
 * Les crédits de la SCI sont saisis avec les autres crédits, rattachés par `sci_id`.
 */
export type Sci = { 
/**
 * Identifiant stable, utilisé par `Dette::sci_id`.
 */
id: string, nom: string, regime: RegimeSci, 
/**
 * Quote-part détenue par le foyer (%) : une SCI est souvent partagée avec des tiers.
 */
part_foyer_pct: number, 
/**
 * Valeur vénale des biens détenus par la SCI.
 */
valeur_biens: number, 
/**
 * Parts de SCPI détenues par la SCI.
 */
scpi: number, loyers_mensuels: number, 
/**
 * Charges mensuelles hors crédit et hors impôt (taxe foncière, gestion, travaux courants).
 */
charges_mensuelles: number, 
/**
 * SCI à l'IS : part du résultat distribuée aux associés (%). Le reste est capitalisé
 * dans la société et ne constitue donc pas un revenu passif du foyer.
 */
distribution_pct: number, };
