// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AllocationEtudes } from "./AllocationEtudes";
import type { CategoriePoche } from "./CategoriePoche";
import type { Priorite } from "./Priorite";

/**
 * Sous-poche datée de la poche 1 : études d'un enfant ou projet du foyer.
 */
export type SousPoche = { nom: string, categorie: CategoriePoche, priorite: Priorite, horizon_ans: number, 
/**
 * Coût total en euros d'aujourd'hui.
 */
montant_actuel_eur: number, 
/**
 * Études uniquement : coût annuel en euros d'aujourd'hui.
 */
cout_annuel_actuel_eur: number | null, capital_cible_eur: number, capital_actuel_eur: number, epargne_mensuelle_eur: number, 
/**
 * Si l'horizon est nul : montant manquant immédiatement.
 */
deficit_immediat_eur: number, rendement_attendu: number, allocation: AllocationEtudes, 
/**
 * Années avant le prochain palier du glide path (None si déjà 100 % sécurisé).
 */
prochain_palier_dans_ans: number | null, prochaine_part_actions: number | null, enveloppe: string, };
