// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Synthese = { nb_adultes: number, nb_enfants: number, age_reference: number, tol_risque_retenue: number, p_fin_eur: number, v_immo_loc_eur: number, ratio_immo_locatif: number, taux_endettement: number, tmi_pct: number, };
