// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tranche marginale d'imposition du foyer.
 */
export type Tmi = "0" | "11" | "30" | "41" | "45";
