// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BienVendu } from "./BienVendu";

/**
 * Vente d'un bien immobilier programmée à une échéance.
 */
export type VenteImmobiliere = { libelle: string, bien: BienVendu, 
/**
 * Échéance de la vente, en années à partir d'aujourd'hui.
 */
dans_ans: number, 
/**
 * Part du bien vendue (%) : 100 = vente totale.
 */
part_vendue_pct: number, 
/**
 * Prix de vente attendu, en euros d'aujourd'hui.
 */
prix_vente: number, 
/**
 * Prix d'acquisition, frais d'acquisition et travaux inclus (base de la plus-value).
 */
prix_acquisition: number, 
/**
 * Années de détention déjà écoulées à ce jour (les abattements courent en plus
 * jusqu'à la date de vente).
 */
detention_ans: number, 
/**
 * Frais d'agence et de diagnostics, en % du prix de vente.
 */
frais_vente_pct: number, };
