// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Que faire d'un crédit, une fois son taux comparé au rendement attendu de la poche 2.
 */
export type VerdictCredit = "rembourser" | "arbitrer" | "conserver" | "levier";
